server:
  port: 8207
spring:
  application:
    name: nacos-user-service
  cloud:
    nacos:
      discovery:
        server-addr: a.usts.top:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'