server:
  port: 8308
spring:
  application:
    name: consul-ribbon-service
  cloud:
    consul:
      host: a.usts.top
      port: 8500
      discovery:
        service-name: ${spring.application.name}
service-url:
  consul-user-service: http://consul-user-service